version: '3'

services:
    nginx:
        build:
            context: "./config"
            dockerfile: "dockerFileNginx"
        container_name: nginx
        ports:
            - 80:80
        environment:
            - NGINX_HOST=servershop
            - NGINX_PORT=80
        volumes:
            - ./htdocs:/usr/share/nginx/html/
        networks:
            static-network:
                ipv4_address: 172.100.100.10

    php-fpm:
        build:
            context: "./config"
            dockerfile: "dockerFilePHP-fpm"
        container_name: php
        ports:
            - 9000:9000
        networks:
            static-network:
                ipv4_address: 172.100.100.11


networks:
    static-network:
        ipam:
            driver: default
            config:
                - subnet: 172.100.100.0/24
